export default {
    LOGIN: 'Sign In to your Account',
    ENTER_NUMBER: 'Please enter an active Phone Number',
    PHONE_NUMBER: 'Phone Number',
    COUNTRY_CODE: '+91',
    SUBMIT: 'Submit',
    VERIFY: 'Verify your Phone number',
    OTP_SENT: 'An OTP has been sent to ',
    NOT_RECIEVED: 'OTP Not Recieved? ',
    RESEND: 'Resend OTP',
    NAME: 'Name',
    EMAIL: 'Email',
    ABOUT: 'About',
    MESSAGES: 'Messages',
    CANCEL: 'Cancel',
    SEARCH: 'Search',
    ONLINE: 'Online',
    RECENT: 'RECENT',
    PROFILE_HEADER: "'s Profile",
    GO_BACK: 'Profile Image',
    LOGOUT: 'LogOut',
    NEW_CHAT: 'New Chat',
    STATUS: 'Add Status',
}